repos:
- hooks:
  - exclude: (docs|\.phan)
    id: trailing-whitespace
  - id: end-of-file-fixer
  - exclude: (.vscode)
    id: check-json
  - id: check-xml
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
- hooks:
  - exclude: (tests\/__data-providers__)
    id: php-lint
  - args:
    - --standard=PSR1,PSR12,./phpcs.xml
    - -p
    exclude: (examples|test|\.phan)
    files: \.(php)$
    id: php-cs
  repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.4.0
